### ISSUE TITLE
How to provide imageUrl in function createPin(note, boardId, imageUrl, link, onSuccess, onError)

### ISSUE THREAD

**Issue by tonystaa** [zyramedia/cordova-plugin-pinterest#1]
I can't find a way to provide imageUrl for the image that I have captured using :

> cordova-plugin-camera

I tried passing the FILE_URI provided by this plugin, but I got this error : 

```
message: "Parameter 'image_url' (value file:///storage/emulated/0/Android/data/com.xyzapp.ghera/cache/1511345813897.jpg) is not a valid URL format."
param: "image_url"
type: "api"
```

I tried passing the whole binary value from DATA_URL of image but that also resulted in error.

But when I provided a url from internet it worked.
Please tell me how can I provide image_url of the image from my device

**Comment by ihadeed** [comment]
You need to upload the image somewhere, you can't upload directly to Pinterest through their mobile SDKs.
